<a href="https://colab.research.google.com/github/Kavishka2401/GPTea/blob/C_1_Yield_Prediction/Machine_Learning_Pipeline/01_Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Google Drive to get the datasets
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Import Libraries
import pandas as pd

In [6]:
weather_data_daily_path = '/content/drive/MyDrive/DSGP_DOCS/Datasets/weather_daily_full_features.csv'
yph_fertlizer_data_path     = '/content/drive/MyDrive/DSGP_DOCS/Datasets/Monthly_YPH_Fertilizer.csv'

# Load daily weather data
weather_data_daily = pd.read_csv(weather_data_daily_path)

# Load YPH + fertilizer data
yph_fertlizer_data = pd.read_csv(yph_fertlizer_data_path)

In [7]:
# Check samples
weather_data_daily.head()

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,relative_humidity_2m_max,relative_humidity_2m_min,relative_humidity_2m_mean,precipitation_sum,rain_sum,sunshine_duration,wind_speed_10m_max,wind_speed_10m_mean,et0_fao_evapotranspiration
0,2017-01-01,21.8,15.1,18.9,99,73,91,12.6,12.6,28628.69,6.6,3.8,2.66
1,2017-01-02,22.2,15.3,18.9,92,70,82,2.2,2.2,37685.96,10.2,5.1,2.92
2,2017-01-03,21.9,16.2,19.0,92,74,83,3.1,3.1,33510.66,9.4,5.0,2.81
3,2017-01-04,22.5,14.3,18.8,89,54,66,0.0,0.0,39116.96,12.6,7.6,4.41
4,2017-01-05,21.9,15.7,20.0,73,8,43,0.0,0.0,39166.65,9.7,5.4,4.85

In [8]:
yph_fertlizer_data.head()

,Year,Month,YPH,T200,UT925,U709,Epson Salt,Dolomite,Urea,Zinc,Compost,BioShakthi,BioShield
0,2017,Jan,90.0,600.0,450.0,2000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2017,Feb,124.0,0.0,1700.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2017,Mar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017,Apr,149.0,0.0,12900.0,3250.0,166.5,27350.0,166.5,166.5,0.0,0.0,0.0
4,2017,May,125.0,0.0,12650.0,13250.0,163.0,0.0,163.0,163.0,0.0,0.0,0.0

### **Conversion of Weather Daily Data to Monthly**

In [9]:
# Ensure time column in dataset is datetime
weather_data_daily['time'] = pd.to_datetime(weather_data_daily['time'])

# Extract Year and Month
weather_data_daily['Year'] = weather_data_daily['time'].dt.year
weather_data_daily['Month'] = weather_data_daily['time'].dt.month  # numeric month
weather_data_daily['Month_name'] = weather_data_daily['Month'].apply(lambda x: pd.to_datetime(str(x), format='%m').strftime('%b'))

# Define aggregation
agg_dict = {
    'temperature_2m_max': 'mean',
    'temperature_2m_min': 'mean',
    'temperature_2m_mean': 'mean',
    'relative_humidity_2m_max': 'mean',
    'relative_humidity_2m_min': 'mean',
    'relative_humidity_2m_mean': 'mean',
    'precipitation_sum': 'sum',
    'rain_sum': 'sum',
    'sunshine_duration': 'sum',
    'wind_speed_10m_max': 'mean',
    'wind_speed_10m_mean': 'mean',
    'et0_fao_evapotranspiration': 'mean'
}

# Group by Year & Month and aggregate
weather_data_monthly = weather_data_daily.groupby(['Year', 'Month', 'Month_name']).agg(agg_dict).reset_index()

# Sort by Year and Month number
weather_data_monthly = weather_data_monthly.sort_values(['Year', 'Month']).reset_index(drop=True)

# Drop numeric Month
weather_data_monthly = weather_data_monthly.drop(columns=['Month'])

# Check result
weather_data_monthly.head()

,Year,Month_name,temperature_2m_max,temperature_2m_min,temperature_2m_mean,relative_humidity_2m_max,relative_humidity_2m_min,relative_humidity_2m_mean,precipitation_sum,rain_sum,sunshine_duration,wind_speed_10m_max,wind_speed_10m_mean,et0_fao_evapotranspiration
0,2017,Jan,22.090323,14.322581,18.412903,93.516129,60.483871,76.903226,201.3,201.3,1037724.72,8.451613,4.516129,3.479032
1,2017,Feb,22.050000,14.414286,18.410714,97.642857,64.357143,83.428571,151.6,151.6,994468.11,7.542857,3.889286,3.722500
2,2017,Mar,22.712903,15.793548,19.248387,98.838710,73.677419,88.451613,221.3,221.3,1113625.83,8.212903,4.074194,3.654516
3,2017,Apr,22.943333,17.436667,20.036667,99.533333,77.666667,90.933333,152.5,152.5,1106964.18,9.070000,4.480000,3.620333
4,2017,May,22.064516,18.177419,19.919355,99.741935,84.612903,94.290323,681.7,681.7,807927.15,10.612903,6.793548,2.560968

In [10]:
# Save to Google Drive
save_path = '/content/drive/MyDrive/DSGP_DOCS/Datasets/weather_monthly.csv'
weather_data_monthly.to_csv(save_path, index=False)
print("Monthly weather data saved successfully!")

Monthly weather data saved successfully!